name: app_review
description: Request and Write Reviews and Open Store Listing for Android and iOS in Flutter.
version: 2.1.2+2
maintainer: Rody Davis (@rodydavis)
homepage: https://github.com/rodydavis/plugins
repository: https://github.com/fluttercommunity/app_review

environment:
  sdk: ">=2.16.0"
  flutter: ^1.10.0

dependencies:
  http: ^0.13.0
  package_info: ^2.0.0
  url_launcher: ^6.0.0-nullsafety.6
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.appleeducate.appreview
        pluginClass: AppReviewPlugin
      ios:
        pluginClass: AppReviewPlugin
